leaderboard_profes/leaderboard_profes/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usuarios.urls')),
    path('', include('opiniones.urls')),
]

leaderboard_profes/opiniones/urls.py
from django.urls import path
from . import views
from usuarios.views import landing_page

app_name = 'opiniones'

urlpatterns = [
    path('', landing_page, name='main'),
    path('opinion-form', views.opinion_form, name='opinion-form'),
    path('opinion-list', views.opinion_list, name='opinion-list'),
]

leaderboard_profes/usuarios/urls.py
from django.urls import path
from . import views

app_name = 'usuarios'

urlpatterns = [
    path('register', views.register_user, name='register_user'), 
    path('login',views.login_user, name='login'),
    path('profile',views.ProfileView.as_view(), name = 'profile'),
    path('cursos', views.list_cursos, name='cursos-list'),
    path('cursos/crear', views.create_curso, name='cursos-create'),
    path('cursos/<int:pk>/', views.view_curso, name='cursos-view'),
    path('landing_page', views.landing_page, name = 'landing_page')
]

leaderboard_profes/opiniones/models.py
from django.db import models
from usuarios.models import Course, Department, User

class Teacher(models.Model):
    teacher_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, null=False, blank=False)
    departments = models.ManyToManyField(Department)

    def __str__(self):
        return self.name

class Opinion(models.Model):
    DIFFICULTY_CHOICES = [(i, i) for i in range(1, 8)]
    THEORICITY_CHOICES = [(i, i) for i in range(1, 8)]
    MATRACA_CHOICES = [(i, i) for i in range(1, 8)]
    TEACHER_SUPPORT_CHOICES = [(i, i) for i in range(1, 8)]

    opinion_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.RESTRICT, null=False)
    course = models.ForeignKey(Course, on_delete=models.RESTRICT, null=False, verbose_name="Curso")
    professor = models.ForeignKey(Teacher, on_delete=models.RESTRICT, null=False, verbose_name="Profesor")
    course_date = models.DateField(auto_now_add=True, verbose_name="Fecha del curso")
    difficulty = models.PositiveIntegerField(choices=DIFFICULTY_CHOICES, verbose_name="Dificultad")
    theoricity = models.PositiveIntegerField(choices=THEORICITY_CHOICES, verbose_name="Teoricidad")
    matraca = models.PositiveIntegerField(choices=MATRACA_CHOICES)
    pauteable = models.BooleanField(null=False, blank=False)
    first_time = models.BooleanField(null=False, blank=False, verbose_name="Primera vez", default=False)
    teacher_support = models.PositiveIntegerField(choices=TEACHER_SUPPORT_CHOICES, verbose_name="Apoyo del profesor")

leaderboard_profes/usuarios/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User

class Major(models.Model):
    major_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50, blank=False, null=False)

    def __str__(self):
        return self.name

class Department(models.Model):
    department_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50, blank=False, null=False)

    def __str__(self):
        return self.name
    
class User(AbstractUser):
    pass

class UcampusUser(models.Model):
    id = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    major = models.ForeignKey(Major, on_delete=models.RESTRICT, null=False)
    ucampus_login = models.CharField(max_length=255, blank=False, null=False)

class Course(models.Model):
    course_id = models.AutoField(primary_key=True) 
    code = models.CharField(max_length=30, unique=True, blank=False, null=False, verbose_name="Código")
    name = models.CharField(max_length=255, verbose_name="Nombre")
    department = models.ForeignKey(Department, on_delete=models.RESTRICT, null=False, verbose_name="Departamento")
    credits = models.PositiveIntegerField()

    @property
    def avg_difficulty(self):
        avg = self.opinion_set.aggregate(models.Avg('difficulty'))['difficulty__avg']
        return avg if avg else 'N/A'

    @property
    def avg_theoricity(self):
        avg = self.opinion_set.aggregate(models.Avg('theoricity'))['theoricity__avg']
        return avg if avg else 'N/A'
    @property
    def avg_matraca(self):
        avg = self.opinion_set.aggregate(models.Avg('matraca'))['matraca__avg']
        return avg if avg else 'N/A'
    @property
    def avg_teacher_support(self):
        avg = self.opinion_set.aggregate(models.Avg('teacher_support'))['teacher_support__avg']
        return avg if avg else 'N/A'

    def __str__(self):
        return f'{self.code} - {self.name}'

leaderboard_profes/opiniones/forms.py
from django import forms
from .models import *

class SubmitOpinion(forms.ModelForm):
    class Meta:
        model = Opinion
        fields = ['course', 'professor', 'difficulty', 'theoricity', 'matraca', 'pauteable', 'teacher_support']

leaderboard_profes/usuarios/forms.py
from django import forms
from .models import *

class SubmitCourse(forms.ModelForm):

    class Meta:
        model = Course
        fields = '__all__'

leaderboard_profes/opiniones/views.py
from django.shortcuts import redirect, render

from opiniones.models import Opinion
from .forms import SubmitOpinion
from usuarios.models import Course
# Create your views here.

def main(request):
   return render(request,"opiniones/base_layout.html")

def opinion_form(request):
   if request.method == "POST":
      form = SubmitOpinion(request.POST)
      if form.is_valid():
         opinion = form.save(commit=False)
         opinion.user = request.user
         opinion.save()
         return redirect('usuarios:cursos-view', pk=opinion.course.pk)
   curso_id = request.GET.get('curso_id')
   if curso_id:
      print('curso id')
      course = Course.objects.get(pk=curso_id)
      form = SubmitOpinion(initial={'course':curso_id})
   else:
      form = SubmitOpinion()
   return render(request,"opiniones/opinion_form.html", {'forms':form})

def opinion_list(request):
   opiniones = Opinion.objects.all()
   return render(request,"opiniones/opinion_list.html", {'opiniones':opiniones})

leaderboard_profes/usuarios/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponseRedirect
from usuarios.models import *
from django import views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login, logout
from .forms import SubmitCourse
from opiniones.views import opinion_form
# Create your views here.

def landing_page(request):
   if request.method == "GET":
      return render(request, "usuarios/index.html")

def register_user(request):
   if request.method == 'GET': 
     return render(request, "usuarios/register_user.html")
   elif request.method == 'POST': 
     nombre = request.POST['nombre']
     contraseña = request.POST['contraseña']
     mail = request.POST['mail']
     user = User.objects.create_user(username=nombre, password=contraseña, email=mail)
     return HttpResponseRedirect('/login')
   
def login_user(request):
    if request.method == 'GET':
        return render(request,"usuarios/login_user.html")
    if request.method == 'POST':
        username = request.POST['username']
        contraseña = request.POST['contraseña']
        usuario = authenticate(username=username,password=contraseña)
        if usuario is not None:
            login(request, usuario)
            return HttpResponseRedirect(reverse_lazy('opiniones:opinion-form'))
        else:
            return HttpResponseRedirect(reverse_lazy('usuarios:register_user'))

class ProfileView(LoginRequiredMixin,views.View):
   login_url = reverse_lazy("login")
   redirect_field_name = "redirect_to"
   
   def get(self,request):
      context = {
         'user': request.user
      }
      return render(request, 'usuarios/profile.html',context)

def list_cursos(request):
   courses = Course.objects.all()
   return render(request,"usuarios/list_cursos.html", {'cursos':courses})

def create_curso(request):
   if request.method == "POST":
      form = SubmitCourse(request.POST)
      if form.is_valid():
         form.save()
         # send to list_cursos
         return redirect('usuarios:cursos-list')
   form = SubmitCourse()
   return render(request,"usuarios/create_curso.html", {'forms':form})

def view_curso(request, pk):
   curso = Course.objects.get(pk=pk)
   return render(request,"usuarios/view_curso.html", {'curso':curso})

leaderboard_profes/opiniones/templates/opiniones/base_layout.html
<head>
  <title>Leaderboard</title>
</head>
<body>
  <div class="grid wrapper">
    <div class="header text-white">
      <h1>U-R8</h1>
      <!-- LOG OUT -->
      <div class="row justify-content-end">
      </div>
    </div>
    <div class="sidebar">
      <h2>Menu</h2>
      <ul>
        <li><a href="{% url 'opiniones:opinion-list' %}">Opiniones</a></li>
        <li><a href="{% url 'usuarios:cursos-list' %}">Cursos</a></li>
      </ul>
      <a href="{% url 'usuarios:landing_page' %}">
        <button class="button">Cerrar sesión</button>
      </a>
    </div>
    <div class="main">{% block content %}{% endblock %}</div>
  </div>
</body>
<style>
  body {
    background-color: #f5f5f5;
    font-family: Helvetica, Arial, sans-serif;
    font-size: 14px;
    color: #333333;
    margin: 0;
    padding: 0;
    /* padding: 1vh 1vw; */
  }
  .grid {
    display: grid;
    grid-template-columns: 1fr 5fr;
    grid-template-rows: 1fr 20fr;
  }
  .wrapper {
    height: 100vh;
  }
  .sidebar {
    grid-column: 1;
    grid-row: 2 / 3;
    background-color: #d8d8d8;
    padding: 2vh 1vw;
  }
  .header {
    grid-column: 1 / 3;
    grid-row: 1;
    background-color: #0275d8;
    padding-left: 1vw;
  }
  .main {
    grid-column: 2;
    grid-row: 2;
  }
  .content {
    background-color: #f5f5f5;
    font-family: Helvetica, Arial, sans-serif;
    font-size: 14px;
    color: #333333;
    padding: 1vh 1vw;
  }
  .row {
    display: flex;
    flex-direction: row;
  }
  .justify-content-center {
    justify-content: center;
  }
  .justify-content-space-between {
    justify-content: space-between;
  }
  .justify-items-center {
    justify-items: center;
  }
  .card {
    background-color: #ffffff;
    border-radius: 0.25rem;
    border: 1px solid rgba(0, 0, 0, 0.125);
    padding: 1vh 1vw;
    margin: 1vh 1vw;
  }
  .card-margin {
    margin: 1vh 10vw;
  }
  .field-wrapper {
    margin: 1vh 0;
  }
  /*
  rojo ucursos: #C62828
  */
  select {
    width: 100%;
    padding: 0.375rem 0.75rem;
    font-size: 1rem;
    line-height: 1.5;
    color: #495057;
    background-color: #f5f5f5;
    background-clip: padding-box;
    border: 1px solid #ced4da;
    border-radius: 0.25rem;
  }
  input[type="text"],
  input[type="number"] {
    width: 100%;
    padding: 0.375rem 0.75rem;
    font-size: 1rem;
    line-height: 1.5;
    color: #495057;
    background-color: #f5f5f5;
    background-clip: padding-box;
    border: 1px solid #ced4da;
    border-radius: 0.25rem;
  }
  input[type="checkbox"] {
    width: 1rem;
    height: 1rem;
  }
  .form-content {
    display: flex;
    flex-direction: column;
    padding: 1vh 0.75rem;
  }
  .card-content {
    display: flex;
    flex-direction: column;
    padding: 1vh 0.75rem;
  }
  label {
    font-weight: bold;
  }
  .submit-wrapper {
    display: flex;
    justify-content: end;
  }
  .button {
    background-color: rgb(98, 153, 103);
    color: #ffffff;
    border: none;
    border-radius: 0.25rem;
    padding: 0.375rem 0.75rem;
    font-size: 1rem;
    margin-top: 2vh;
    margin-bottom: 2vh;
    line-height: 1.5;
    width: 10vw;
    cursor: pointer;
    text-decoration: none;
  }
  .submit-button {
    background-color: rgb(98, 153, 103);
    color: #ffffff;
    border: none;
    border-radius: 0.25rem;
    padding: 0.375rem 0.75rem;
    margin-top: 5vh;
    font-size: 1rem;
    line-height: 1.5;
    width: 10vw;
    cursor: pointer;
  }
  .button:hover {
    background-color: rgb(98, 153, 103, 0.8);
  }
  .submit-button:hover {
    background-color: rgb(98, 153, 103, 0.8);
  }
  .full-width {
    width: 100%;
  }

  .text-white {
    color: #ffffff;
  }

  .menu-item {
    list-style-type: none;
    padding: 0.5vh 0;
  }
  .base-table {
    width: 100%;
    border-collapse: collapse;
  }
  .table-head {
    background-color: #0275d8;
    color: #ffffff;
  }
  thead {
    border-top-left-radius: 5px;
    border-top-right-radius: 5px;
  }
  th {
    text-align: left;
    padding: 10px;
  }
  th:first-child {
    border-top-left-radius: 5px;
  }
  th:last-child {
    border-top-right-radius: 5px;
  }
  td {
    padding: 10px;
    border-bottom: 1px solid #ddd;
  }
  td {
    border-right: 1px solid #ddd;
    border-left: 1px solid #ddd;
  }
  tbody {
    border-left: 1px solid #ddd;
    border-right: 1px solid #ddd;
  }
  tbody tr:nth-child(even) {
    background-color: #f2f2f2;
  }
  tbody tr:hover {
    background-color: #f0f0f0;
  }
  .list-wrapper {
    padding: 2vh 0vw;
  }
  .list-wrapper-nested {
    padding-bottom: 2vh;
  }
  .action-button {
    background-color: rgb(117, 117, 117);
    color: #ffffff;
    border: none;
    border-radius: 0.25rem;
    font-size: 1rem;
    margin-top: 2vh;
    margin-bottom: 2vh;
    line-height: 1.5;
    width: 5vw;
    cursor: pointer;
    text-decoration: none;
  }
  .button-primary {
    background-color: #0275d8;
  }
  .button-primary:hover {
    background-color: #0275d8;
  }
  .cell-center {
    text-align: center;
  }
  .detail-caption {
    font-size: 0.8rem;
    font-weight: bold;
  }
  .detail-text-big {
    font-size: 1.2rem;
    font-weight: bold;
  }
  .detail-text {
    font-size: 1rem;
  }
  .details-container {
    padding: 2vh 0vw;
  }
  .detail-info > div {
    margin-bottom: 1vh;
  }
  .list-title {
    font-size: 1.2rem;
    font-weight: bold;
    margin-top: 2vh;
  }
  .pb-md {
    padding-bottom: 2vh;
  }
</style>

leaderboard_profes/opiniones/templates/opiniones/opinion_form.html
<head>
    <title>Opiniones</title>
  </head>
  <body>
    {% extends "opiniones/base_layout.html" %} {% block content %}
    <div class="content">
      <div class="row justify-content-center">
        <div class="card full-width card-margin">
          <h1 class="bg-red col-12">Ingresar una opinión</h1>
        </div>
      </div>
      <div class="card card-margin">
        <form method="post">
          {% csrf_token %} {% for field in forms %}
          <div class="field-wrapper">
            {{ field.errors }} {{ field.label_tag }} {{ field }}
          </div>
          {% endfor %}
          <div class="submit-wrapper">
            <input type="submit" value="Enviar" class="submit-button" />
          </div>
        </form>
      </div>
    </div>
    {% endblock %}
  </body>
  <style></style>
  

leaderboard_profes/opiniones/templates/opiniones/opinion_list.html
<head>
  <title>Opiniones</title>
</head>
<body>
  {% extends "opiniones/base_layout.html" %} {% block content %}
  <div class="content">
    <div class="row justify-content-center">
      <div class="card full-width card-margin">
        <div class="row justify-content-space-between">
          <h1 class="col-12">Opiniones</h1>
          <a href="{% url 'opiniones:opinion-form' %}">
            <button class="button">Crear</button>
          </a>
        </div>
      </div>
    </div>
    <div class="card card-margin">
      <div class="list-wrapper">
        <table class="base-table">
          <thead class="table-head">
            <tr>
              <th>Curso</th>
              <th>Profesor</th>
              <th>Dificultad</th>
              <th>Teoricidad</th>
              <th>Matraca</th>
              <th>Pauteable</th>
              <th>Apoyo del profesor</th>
            </tr>
          </thead>
          <tbody>
            {% for opinion in opiniones %}
            <tr>
              <td>{{opinion.course}}</td>
              <td>{{opinion.professor}}</td>
              <td>{{opinion.difficulty}}</td>
              <td>{{opinion.theoricity}}</td>
              <td>{{opinion.matraca}}</td>
              <td>
                {% if opinion.pauteable == True %} Si {% else %} No {% endif %}
              </td>
              <td>{{opinion.teacher_support}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
  {% endblock %}
</body>
<style></style>

leaderboard_profes/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type = "text/css" href=" static\usuarios\style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>{%block title %}Leaderboard{% endblock %}</title>
    <link rel="stylesheet" href="{%static base.css %}">
  </head>
  <body>
    <div class="grid wrapper">
      <header data-bs-theme="dark">
        <h1>Leaderboard de profes 🔥</h1>
        <nav class="navbar navbar-expand-ld navbar-primary fixed-top bg-primary">
            <div class="container-fluid">
            <a class="navbar-brand" href="#">U-R8</a>
                <div class="text-end">
                <a href="{% url 'usuarios:login' %}">
                    <button type="button" class="btn btn-outline-light me-2">Login</button>
                </a>
                <a href="{% url 'usuarios:register_user' %}">
                    <button type="button" class="btn btn-light" >Registrarse</button>
                </a>
                </div>
            </div>
        </nav>
      </header>
      <nav class="sidebar">
        <h2>Menú</h2>
        <ul>
          <li><a href="{% url 'opiniones:opinion-list' %}">Opiniones</a></li>
          <li><a href="{% url 'usuarios:cursos-list' %}">Cursos</a></li>
        </ul>
      </nav>
      <main class="bg-white text-light p-5 text-center text-sm-start py-20">{% block content %}{% endblock %}</main>
    </div>
  </body>
</html>

leaderboard_profes/templates/index.html
{% extends "base.html" %}
{% block main %}
<div class="container">
    <div class="d-sm-flex align-items-center justify-content-between">
    <div>
        <h1 class ="text-dark">Califica a tu <span class="text-primary"> Profesor Favorito </span></h1>
        <p class="lead my-4 text-dark">
        Dicen que un buen profesor puede hacer que ames u odies una asignatura. Nuestro objetivo, es crear
        una plataforma que potencie la enseñanza con los mejores educadores en base a calificaciones de la propia
        comunidad.
        </p>
        <a href="{% url 'usuarios:register_user' %}">
        <button class="btn btn-primary btn-lg" >Registrate y aprende más!</button>
        </a>
    </div>
        <img class="img-fluid w-50 d-none d-sm-block" 
        src="https://img.freepik.com/free-vector/studying-concept-illustration_114360-1301.jpg" alt=""/>
    </div>
</div>
{% endblock %}

leaderboard_profes/usuarios/templates/usuarios/create_curso.html
<head>
  <title>Cursos</title>
</head>
<body>
  {% extends "opiniones/base_layout.html" %} {% block content %}
  <div class="content">
    <div class="row justify-content-center">
      <div class="card full-width card-margin">
        <h1 class="bg-red col-12">Ingresar un curso</h1>
      </div>
    </div>
    <div class="card card-margin">
      <form method="post">
        {% csrf_token %} {% for field in forms %}
        <div class="field-wrapper">
          {{ field.errors }} {{ field.label_tag }} {{ field }}
        </div>
        {% endfor %}
        <div class="submit-wrapper">
          <input type="submit" value="Enviar" class="submit-button" />
        </div>
      </form>
    </div>
  </div>
  {% endblock %}
</body>
<style></style>

leaderboard_profes/usuarios/templates/usuarios/index.html
<!DOCTYPE html>
    <html lang="en" data-bs-theme = "light">
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" type = "text/css" href=" static\usuarios\style.css">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <title>U-R8</title>
    </head>
    
    <body>
        <header data-bs-theme="dark">
            <nav class="navbar navbar-expand-ld navbar-primary fixed-top bg-primary">
              <div class="container-fluid">
                <a class="navbar-brand" href="#">U-R8</a>
                  <div class="text-end">
                    <a href="{% url 'usuarios:login' %}">
                        <button type="button" class="btn btn-outline-light me-2">Login</button>
                    </a>
                    <a href="{% url 'usuarios:register_user' %}">
                        <button type="button" class="btn btn-light" >Registrarse</button>
                    </a>
                  </div>
              </div>
            </nav>
        </header>
        <section class="bg-white text-light p-5 text-center text-sm-start py-20">
          <div class="container">
              <div class="d-sm-flex align-items-center justify-content-between">
              <div>
                  <h1 class ="text-dark">Califica a tu <span class="text-primary"> Profesor Favorito </span></h1>
                  <p class="lead my-4 text-dark">
                  Dicen que un buen profesor puede hacer que ames u odies una asignatura. Nuestro objetivo, es crear
                  una plataforma que potencie la enseñanza con los mejores educadores en base a calificaciones de la propia
                  comunidad.
                  </p>
                  <a href="{% url 'usuarios:register_user' %}">
                  <button class="btn btn-primary btn-lg" >Registrate y aprende más!</button>
                  </a>
              </div>
                  <img class="img-fluid w-50 d-none d-sm-block" 
                  src="https://img.freepik.com/free-vector/studying-concept-illustration_114360-1301.jpg" alt=""/>
              </div>
          </div>
        </section>
    </body>
    </html>

leaderboard_profes/usuarios/templates/usuarios/list_cursos.html
<head>
  <title>Cursos</title>
</head>
<body>
  {% extends "opiniones/base_layout.html" %} {% block content %}
  <div class="content">
    <div class="row justify-content-center">
      <div class="card full-width card-margin">
        <div class="row justify-content-space-between">
          <h1 class="col-12">Cursos</h1>
          <a href="{% url 'usuarios:cursos-create' %}">
            <button class="button">Crear</button>
          </a>
        </div>
      </div>
    </div>
    <div class="card card-margin">
      <div class="list-wrapper">
        <table class="base-table">
          <thead class="table-head">
            <tr>
              <th>Código</th>
              <th>Nombre</th>
              <th>Departamento</th>
              <th>Creditos</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {% for curso in cursos %}
            <tr>
              <td>{{curso.code}}</td>
              <td>{{curso.name}}</td>
              <td>{{curso.department}}</td>
              <td>{{curso.credits}}</td>
              <td class="cell-center">
                <a href="{% url 'usuarios:cursos-view' curso.pk %}">
                  <button class="action-button button-primary">Ver</button>
                </a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <div></div>
    </div>
  </div>
  {% endblock %}
</body>
<style></style>

leaderboard_profes/usuarios/templates/usuarios/login_user.html
<!DOCTYPE html>
    <html lang="en" data-bs-theme = "light">
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" type = "text/css" href=" static\usuarios\style.css">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <title>Login</title>
    </head>
    <body class = "d-flex align-items-center py-4 bg-body-tertiary">
        <header data-bs-theme="dark">
            <nav class="navbar navbar-expand-ld navbar-primary fixed-top bg-primary">
              <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'usuarios:landing_page' %}">U-R8</a>
              </div>
            </nav>
        </header>
        <main class ="form-signing m-auto">
            <form method="post">
                <h1 class = "titulo"> Iniciar Sesión </h1>
                {% csrf_token %}
                <div class = "form-floating">
                    <input type="text" class="form-control" id="floatingInput" name="username" placeholder = "Usuario" required>
                    <label for="floatingInput">Nombre de usuario</label>
                </div>    
                <div class = "form-floating">
                    <input type="password" class="form-control" id="floatingPassword" name="contraseña" placeholder = "Contraseña" required>
                    <label for="floatingPassword">Contraseña</label>
                </div>
                <button type="submit" class = "btn btn-primary w-100 py-2">Login</button>
            </form>
            <a href="{% url 'usuarios:register_user' %}"> No tienes Cuenta? Registrate!</a>
        </main>
    </body>
    </html>

leaderboard_profes/usuarios/templates/usuarios/profile.html
{% block content %}



<h2>{% block title %} Profile {% endblock %}</h2>
<p>Username: {{ user }} </p>
<p>Email: {{ user.email }} </p>

{% endblock %}

leaderboard_profes/usuarios/templates/usuarios/register_user.html
<!DOCTYPE html>
    <html lang="en" data-bs-theme = "light">
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" type = "text/css" href=" static\usuarios\style.css">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <title>Registro</title>
    </head>
    <body class = "d-flex align-items-center py-4 bg-body-tertiary">
        <header data-bs-theme="dark">
            <nav class="navbar navbar-expand-ld navbar-primary fixed-top bg-primary">
              <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'usuarios:landing_page' %}">U-R8</a>
              </div>
            </nav>
        </header>
        <main class ="form-signing m-auto">
            <form method="post">
                <h1 class = "titulo"> Registro </h1>
                {% csrf_token %}
                <div class = "form-floating">
                    <input type="text" class="form-control" id="floatingInput" name="nombre" placeholder = "Nombre de Usuario" required>
                    <label for="floatingInput">Nombre de Usuario</label>
                </div>    
                <div class = "form-floating">
                    <input type="password" class="form-control" id="floatingPassword" name="contraseña" placeholder = "Contraseña" required>
                    <label for="floatingPassword">Contraseña</label>
                </div>
                <div class="form-floating">
                    <input type="email" class="form-control" id="floatingEmail" name="mail" placeholder = "Mail" required>
                    <label for="mail">Mail</label>
               </div>
                <button type="submit" class = "btn btn-primary w-100 py-2">Register</button>
            </form>
            <a href="{% url 'usuarios:login' %}"> Ya tienes Cuenta? Entra!</a>
        </main>
     </body>
     </html>